:attribute_definitions:
  -
    :attribute_name: key
    :attribute_type: S

:table_name: hackday

:key_schema:
  -
    :attribute_name: key
    :key_type: HASH

:provisioned_throughput:
  :read_capacity_units: 10
  :write_capacity_units: 10
