---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    CnameEntry:
      Type: "String"
      Description: "The cname entry for the component"
      Default: "release-news"
    ServiceHostedZoneName:
      Type: "String"
      Description: "Base domain name (ending with a '.') under which new service DNS entries are added"
      Default: "cloud.bbc.co.uk."
    ServiceEnvironment:
      Type: "String"
      Description: "Environment name with leading and trailing dots (e.g. '.int.', '.test.'). For your live component use '.' instead of '.live.'."
      AllowedPattern: "\\.(?:(?!live\\.)\\w+\\.)?"
      Default: ".int."
    Backend:
      Type: "String"
      Description: "The backend service to point the CNAME entry at"
      Default: "release-news.int.7808afff336f64a7.xhst.bbci.co.uk"
  Resources:
    ServiceComponentDNS:
      Type: "AWS::Route53::RecordSet"
      Properties:
        HostedZoneName:
          Ref: "ServiceHostedZoneName"
        ResourceRecords:
          -
            Ref: "Backend"
        Type: "CNAME"
        Name:
          Fn::Join:
            - ""
            -
              -
                Ref: "CnameEntry"
              -
                Ref: "ServiceEnvironment"
              -
                Ref: "ServiceHostedZoneName"
        TTL: 60
