cloudformation:
  core_infrastructure: &core_infrastructure
    VpcId: vpc-ef916f8a
    PrivateSubnet1Id: subnet-4397761a
    PrivateSubnet2Id: subnet-166cc873
    PrivateSubnet3Id: subnet-4d9b593a
    PublicSubnet1Id: subnet-4297761b
    PublicSubnet2Id: subnet-176cc872
    PublicSubnet3Id: subnet-4e9b5939
    ImageId: ami-33734044
    BastionAccessSecurityGroup: sg-176fc272
    KeyName: cosmos
    Environment: int

  shared: &component_shared
    UpdatePauseTime: PT0S
    UpdateMaxBatchSize: 1
    UpdateMinInService: 0
    MinSize: 1
    MaxSize: 1
    InstanceType: t2.small
    AccountDomainNameBase: 7808afff336f64a7.xhst.bbci.co.uk.

  components:
    news-release:
      main:
        account_id: "755368653476"
        variants:
          default:
            <<: *component_shared
            <<: *core_infrastructure
            CnameEntry: release-news.int
            CPUAlarmHighEvalPeriods: "1"
            CPUAlarmHighThreshold: "80"
            CPUAlarmLowEvalPeriods: "5"
            CPUAlarmLowThreshold: "60"
            AlarmPeriod: "60"
            HealthCheckGracePeriod: 600 # 10 minutes
            ELBConnectionDraining: 30 # seconds

      dns:
        account_id: "511603603783"
        variants:
          default:
            CnameEntry: release-news
            ServiceHostedZoneName: api.bbci.co.uk.
            ServiceEnvironment: .int.
            Backend: release-news.int.7808afff336f64a7.xhst.bbci.co.uk
